export enum SYSTEMTYPE {
  ADMIN = 'ADMIN',
  BIGSCREEN = 'BIGSCREEN',
}

// 消除魔法字符串
export enum CONST {
  LOGIN_MESSAGES = 'LOGIN_MESSAGES',
  CURRENT_SYSTEMTYPE = 'CURRENT_SYSTEMTYPE',

  // menu
  SELECTKEYS = 'SELECTKEYS',
  OPENKEYS = 'OPENKEYS',

  // 表格-操作-按钮类型
  TABLE_OPERATE_ADD = 'TABLE_OPERATE_ADD', // 添加
  TABLE_OPERATE_DEL = 'TABLE_OPERATE_DEC', // 删除
  TABLE_OPERATE_UPD = 'TABLE_OPERATE_UPD', // 更新
}