export enum SYSTEMTYPE {
  ADMIN = 'ADMIN',
  BIGSCREEN = 'BIGSCREEN',
}

// 消除魔法字符串
export enum CONST {
  SELECTKEYS = 'SELECTKEYS',
  OPENKEYS = 'OPENKEYS',
  LOGIN_MESSAGES = 'LOGIN_MESSAGES',
  CURRENT_SYSTEMTYPE = 'CURRENT_SYSTEMTYPE',
}