const actionType = {
  SYSTEM_TYPE: 'SYSTEM_TYPE',
  GET_LOGIN_MESSAGE: 'GET_LOGIN_MESSAGE',
  GETLASTBREADCRUMBUSEPARAMS: 'GETLASTBREADCRUMBUSEPARAMS', // 弃用
  GET_ROUTE_PARAMS: 'GET_ROUTE_PARAMS'
}

export default actionType